# Generated by Django 5.0.7 on 2024-08-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cus',
            field=models.FileField(null=True, upload_to='imagenes/', verbose_name='cus'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='isa',
            field=models.FileField(null=True, upload_to='user_documents/', verbose_name='isa'),
        ),
    ]
